# `sudo chown -R 472:472 ${GRAFANA_DATA_PATH}`
# check: docker-compose --env-file=docker.env -f docker-grafana.yml config
# run: docker-compose --env-file=docker.env -f docker-grafana.yml up --build

services:

  mongodb:
    image: mongo:${MONGODB_IMAGE_TAG}  # Use the MongoDB version specified in docker.env
    container_name: mongodb
    env_file:
      - docker.env    # Load non-sensitive information
    volumes:
      - ${MONGODB_DATA_PATH}:/data/db  # Persistent storage for MongoDB data, defined in docker.env
    ports:
      - "27017:27017"

  grafana:
    image: grafana/grafana:${GRAFANA_IMAGE_TAG} # Use the Grafana version specified in docker.env
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ${GRAFANA_DATA_PATH}:/var/lib/grafana  # Persistent storage for Grafana data, defined in docker.env
    env_file:
      - docker.env  # Load non-sensitive information
    environment:
      - GF_INSTALL_PLUGINS=grafana-mongodb-datasource
      - GF_DATABASES_NAME=MongoDB
      - GF_DATABASES_TYPE=mongodb
      - GF_DATABASES_URL=${MONGODB_URI_DOCKER} # see docker.env
      - GF_DATABASES_ACCESS=proxy
    depends_on:
      - mongodb

volumes:
  mongodb_data:
  grafana_data:
