# build & run: docker-compose --env-file=docker.env up --build

services:

  mongodb:
    image: mongo:${MONGODB_IMAGE_TAG}  # Use the MongoDB version specified in docker.env
    container_name: mongodb
    env_file:
      - docker.env    # Load non-sensitive information
    volumes:
      - ${MONGODB_DATA_PATH}:/data/db  # Persistent storage for MongoDB data, defined in docker.env
    ports:
      - "27017:27017"

  chatbot:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: chatbot
    ports:
      - "8501:8501"
    environment:
      - PIP_NO_CACHE_DIR=off
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - mongodb

  dashboard:
    build:
      context: ./
      dockerfile: ./dashboard/Dockerfile
    container_name: dashboard
    ports:
      - "8080:8080"
    environment:
      - PIP_NO_CACHE_DIR=off
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - mongodb

volumes:
  mongodb_data:
