services:
  mongodb:
    image: mongo:${MONGODB_IMAGE_TAG}  # Use the MongoDB version specified in docker.env
    container_name: mongodb
    env_file:
      - .env          # Load sensitive information
      - docker.env    # Load non-sensitive path information
    volumes:
      - ${MONGODB_DATA_PATH}:/data/db  # Persistent storage for MongoDB data, defined in docker.env
    ports:
      - "27017:27017"

volumes:
  mongodb_data:
