[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 120

[tool.ruff]
line-length = 120
select = ["E", "F", "I", "W"]
ignore = ["E501"]


[tool.mypy]
disable_error_code = ["import-untyped"]
